[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
ai_core = { path = "../../core" }
anyhow = "1"
tracing = "0.1"

# CLI
clap = { version = "4.5", features = ["derive"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
