[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
ai_core = { path = "../../core" }
clap = { version = "4", features = ["derive"] }
tracing = "0.1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
